### ISSUE TITLE
Midnight rendering error

### ISSUE THREAD

**Issue by KaeferD** [Grible/timetable.js#3]
It seems there is a bug, when a Events starts at Midnight and the scope is set for example 23 to 3.

Events that start at midnight or later will geht a negative difference on `computeEventBlockOffset()` and won't show on the timetable. To fix this i have edited the function to get the offset of hours (i know there might be a better way to do this, but it works for me)

```
function computeEventBlockOffset(event) {
    var start = event.startDate;
    var startHours = start.getHours() + (start.getMinutes() / 60);
    var hoursDiff = startHours - timetable.scope.hourStart;
    if(hoursDiff < 0){
        hoursDiff = 24 + hoursDiff;
    }
    return hoursDiff / scopeDurationHours * 100 + '%';
}
```

**Comment by stevenaanen** [comment]
Thanks for notifying about this issue @KaeferD. I will try to reproduce the problem by adding an event like that to the demo, and then compare your solution to the current code.

**Comment by Daltonstudio** [comment]
This is kinda buggy. If the event is after midnight. I need to use 00,30 to 01,20 for example, but if it's overlapping midnight the hours need to be 23,30 to 24,30 or it doesn't render. So depending on that I either need to use 00 as 'midnight' or 24.

I have my script doing this, since all my events are coming out a database with the same type of noting midnight, but that's probably a bug, no?
